# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import notify_pb2 as notify__pb2


class NotificationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NotifyEvent = channel.unary_unary(
                '/notification.Notification/NotifyEvent',
                request_serializer=notify__pb2.NotifyRequest.SerializeToString,
                response_deserializer=notify__pb2.NotifyReply.FromString,
                )


class NotificationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NotifyEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NotifyEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyEvent,
                    request_deserializer=notify__pb2.NotifyRequest.FromString,
                    response_serializer=notify__pb2.NotifyReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notification.Notification', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Notification(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NotifyEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notification.Notification/NotifyEvent',
            notify__pb2.NotifyRequest.SerializeToString,
            notify__pb2.NotifyReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
